export const AUTH = 'AUTH';

export const PARKING_LOADING = 'PARKING_LOADING';
export const PARKING_FETCH_ERROR = 'PARKING_FETCH_ERROR';
export const PARKING_FETCH_SUCCESS = 'PARKING_FETCH_SUCCESS';
export const PARKING_CHANGE_ERROR = 'PARKING_CHANGE_ERROR';
export const PARKING_CHANGING = 'PARKING_CHANGING';
export const PARKING_CHANGE_SUCCESS = 'PARKING_CHANGE_SUCCESS';

export const STATISTICS_FETCH_NUM_USER_PARKING_SUCCESS='STATISTICS_FETCH_NUM_USER_PARKING_SUCCESS';
export const STATISTICS_FETCH_NUM_USER_PARKING_ERROR='STATISTICS_FETCH_NUM_USER_PARKING_ERROR';
export const STATISTICS_FETCHING_NUM_USER_PARKING='STATISTICS_FETCHING_NUM_USER_PARKING';