export const AUTH = 'AUTH';
export const PARKING_LOADING = 'PARKING_LOADING';
export const PARKING_FETCH_ERROR = 'PARKING_FETCH_ERROR';
export const PARKING_FETCH_SUCCESS = 'PARKING_FETCH_SUCCESS';
export const PARKING_CHANGE_ERROR = 'PARKING_CHANGE_ERROR';
export const PARKING_CHANGING = 'PARKING_CHANGING';
export const PARKING_CHANGE_SUCCESS = 'PARKING_CHANGE_SUCCESS';